#define NVIDIA_VRWORKS_GRAPHICS_VERSION_MAJOR 3
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_MINOR 4
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_RELEASE 8


#define NVIDIA_VRWORKS_GRAPHICS_VERSION 3,4,8,0
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_MAJOR_MINOR 3,4
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_STRING "3.4.8.0"
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_STRING_SHORT "3.4.8"
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_STRING_MAJOR_MINOR "3.4"
